# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 07:12
from __future__ import unicode_literals

import AlertManager.models
import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
                name='EmailAlerts',
                fields=[
                    ('subject', models.TextField(auto_created=True, blank=True, default='Library Alert',
                                                 help_text='Subject of the email', max_length=200,
                                                 verbose_name='Subject')),
                    ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('sender',
                     django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254, null=True),
                                                               default=AlertManager.models.EmailAlerts.default_email_sender,
                                                               size=None, verbose_name='From')),
                    ('recipient', django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(blank=True, max_length=254, null=True),
                        default=AlertManager.models.EmailAlerts.default_email_sender, null=True, size=None,
                        verbose_name='To')),
                    ('reply_expected', models.BooleanField(default=False,
                                                           help_text='Specify Whether the Recipient can reply to the email.')),
                    ('header', models.TextField(default='LibraryBuddy<br>An Easy Way to Manage your Community Library',
                                                help_text='Header of the Email', verbose_name='Header')),
                    ('footer', models.TextField(default='Yours Faithfully,<br>LibraryBuddy', help_text='Signature',
                                                verbose_name='Signature of the Email')),
                    ('date', models.DateTimeField(auto_now_add=True)),
                    ('body', models.TextField(default='Hello There')),
                    ('title', models.CharField(default='<django.db.models.fields.TextField>',
                                               help_text='Please specify a title for reusing this template in the future',
                                               max_length=300, verbose_name='Email Template Reference Title')),
                ],
        ),
        migrations.CreateModel(
                name='EmailClient',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('client_name',
                     models.CharField(blank='True', default='Library Email Client', max_length=60, null='False')),
                ],
        ),
    ]
