# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookManager', '0001_initial'),
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookManager.Book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Member')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Librarian')),
                ('lend_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                      to='UserManager.Membership')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Returning',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_date', models.DateTimeField(auto_now_add=True)),
                ('penalty_charged', models.FloatField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookManager.Book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Member')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Librarian')),
            ],
                options={
                    'abstract': False,
                },
        ),
    ]
