# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('UserManager', '0001_initial'),
        ('BookManager', '0002_auto_20171012_0612'),
    ]

    operations = [
        migrations.CreateModel(
                name='Lend',
                fields=[
                    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('issue_date', models.DateTimeField(auto_now_add=True)),
                    ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='BookManager.Books')),
                    ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='UserManager.Member')),
                    ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='UserManager.Librarian')),
                ],
        ),
        migrations.CreateModel(
                name='Returning',
                fields=[
                    ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                    ('returned_date', models.DateTimeField(auto_now_add=True)),
                    ('penalty_charged', models.FloatField()),
                    ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='UserManager.Librarian')),
                    ('lend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='TransactionManager.Lend')),
                ],
        ),
    ]
