# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManager', '0001_initial'),
        ('BookManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('primary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookManager.Book')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Member')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Librarian')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Returning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_date', models.DateTimeField(auto_now_add=True)),
                ('penalty_charged', models.FloatField()),
                ('lending_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TransactionManager.Lend')),
            ],
        ),
    ]
