# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
        ('TransactionManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lend',
            name='lend_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManager.Membership'),
        ),
    ]
