# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionManager', '0002_remove_lend_lend_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lend',
            old_name='book',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='returning',
            old_name='book',
            new_name='archive',
        ),
    ]
