# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 22:20
from __future__ import unicode_literals

import TransactionManager.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionManager', '0002_lend_lend_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returning',
            name='lending_record',
            field=models.ForeignKey(default=TransactionManager.models.derive_lend_record, null=True, on_delete=django.db.models.deletion.CASCADE, to='TransactionManager.Lend'),
        ),
    ]
