# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionManager', '0003_auto_20171025_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='returning',
            name='issue_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
