# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionManager', '0005_lend_returning_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returning',
            name='returned_date',
            field=models.DateTimeField(null=True),
        ),
    ]
