# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TransactionManager', '0006_auto_20171025_0753'),
    ]

    operations = [
        migrations.AddField(
                model_name='lend',
                name='returning_date',
                field=models.DateTimeField(default=datetime.datetime(2017, 12, 5, 16, 29, 52, 643682)),
        ),
        migrations.AddField(
                model_name='returning',
                name='returning_date',
                field=models.DateTimeField(default=datetime.datetime(2017, 12, 5, 16, 29, 52, 643682)),
        ),
        migrations.AlterField(
                model_name='lend',
                name='issue_date',
                field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
                model_name='returning',
                name='issue_date',
                field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
