# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 15:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
	dependencies = [
		('TransactionManager', '0013_auto_20171112_1553'),
	]

	operations = [
		migrations.AlterField(
				model_name='lend',
				name='returning_date',
				field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 15, 51, 12, 258991, tzinfo=utc)),
		),
		migrations.AlterField(
				model_name='returning',
				name='returning_date',
				field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 15, 51, 12, 258991, tzinfo=utc)),
		),
	]
