# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 19:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=63)),
                ('middle_name', models.CharField(help_text='Middle Name', max_length=63)),
                ('last_name', models.CharField(help_text='Last Name', max_length=63)),
                ('age', models.IntegerField(help_text='Age of the User eg 18')),
                ('occupation', models.CharField(choices=[('engineer', 'Engineer'), ('doctor', 'Doctor'), ('student', 'Student'), ('researcher', 'Researcher'), ('home_maker', 'Home Maker'), ('artist', 'Artist'), ('management', 'Manager'), ('entrepreneur', 'Entrepreneur'), ('teacher', 'Teacher'), ('other', 'Other')], help_text='Select the Occupation of the User', max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('twitter_handle', models.CharField(max_length=20)),
                ('membership', models.BooleanField()),
                ('membership_type', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('entry_log', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(auto_now=True), size=None)),
                ('lending_log', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
            ],
        ),
    ]
