# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_auto_20171010_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pages', 'Pages'), ('technician', 'Library Technician'), ('librarian', 'Librarian'), ('manager', 'Manager'), ('director', 'Director')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_fee', models.FloatField(help_text='Amount which is needed to be paid to get a membership in the library')),
                ('validity', models.CharField(choices=[('1yr', '1 year'), ('2yr', '2 year'), ('lifetime', 'lifetime')], help_text='Validity of the Type of a Membership', max_length=10)),
                ('lending_power', models.IntegerField()),
                ('type', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=10)),
            ],
        ),
    ]
