# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserManager', '0004_auto_20171103_1450'),
    ]

    operations = [
        migrations.AlterField(
                model_name='member',
                name='membership',
                field=models.NullBooleanField(verbose_name='Is a Member?'),
        ),
    ]
