# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 20:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='ISBN Identifier of the book', max_length=15)),
                ('asin', models.CharField(help_text='ASIN Identifier of the book', max_length=15)),
                ('title', models.CharField(help_text='Book Title', max_length=100)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('publisher', models.CharField(max_length=30)),
                ('published_date', models.DateField()),
                ('publication_type', models.CharField(max_length=30)),
                ('languages', models.CharField(max_length=30)),
                ('cover', models.ImageField(upload_to=b'')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('is_available', models.BooleanField(default=True)),
                ('lending_log', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None)),
            ],
        ),
    ]
