# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='digitalrecords',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
