# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BookManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
                model_name='books',
                name='penalty',
                field=models.FloatField(default=1),
                preserve_default=False,
        ),
        migrations.AddField(
                model_name='digitalrecords',
                name='penalty',
                field=models.FloatField(default=1),
                preserve_default=False,
        ),
        migrations.AddField(
                model_name='journals',
                name='penalty',
                field=models.FloatField(default=1),
                preserve_default=False,
        ),
    ]
