# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 05:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='lending_log',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
