# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookManager', '0002_auto_20171025_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='autocomplete_using_isbn',
            field=models.BooleanField(default=True, help_text='Check this box to autocomplete the book data using ISBN', verbose_name='AutoComplete Using ISBN'),
        ),
        migrations.AddField(
            model_name='digitalrecords',
            name='autocomplete_using_isbn',
            field=models.BooleanField(default=True, help_text='Check this box to autocomplete the book data using ISBN', verbose_name='AutoComplete Using ISBN'),
        ),
        migrations.AddField(
            model_name='journal',
            name='autocomplete_using_isbn',
            field=models.BooleanField(default=True, help_text='Check this box to autocomplete the book data using ISBN', verbose_name='AutoComplete Using ISBN'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='autocomplete_using_isbn',
            field=models.BooleanField(default=True, help_text='Check this box to autocomplete the book data using ISBN', verbose_name='AutoComplete Using ISBN'),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='autocomplete_using_isbn',
            field=models.BooleanField(default=True, help_text='Check this box to autocomplete the book data using ISBN', verbose_name='AutoComplete Using ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='identifier',
            field=models.CharField(choices=[('isbn', 'ISBN'), ('asin', 'ASIN'), ('issn', 'ISSN'), ('doi', 'DOI'), ('lccn', 'LCCN'), ('oclc', 'OCLC')], default='isbn', help_text='Select the type of Identifier<div class="right-align"><button type="submit" value="Save and add another" class="waves-effect waves-light btn white-text" name="_continue">Autocomplete</button></div>', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Title', help_text='Book Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='digitalrecords',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='digitalrecords',
            name='identifier',
            field=models.CharField(choices=[('isbn', 'ISBN'), ('asin', 'ASIN'), ('issn', 'ISSN'), ('doi', 'DOI'), ('lccn', 'LCCN'), ('oclc', 'OCLC')], default='isbn', help_text='Select the type of Identifier<div class="right-align"><button type="submit" value="Save and add another" class="waves-effect waves-light btn white-text" name="_continue">Autocomplete</button></div>', max_length=10),
        ),
        migrations.AlterField(
            model_name='digitalrecords',
            name='title',
            field=models.CharField(default='Title', help_text='Book Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalrecords',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='identifier',
            field=models.CharField(choices=[('isbn', 'ISBN'), ('asin', 'ASIN'), ('issn', 'ISSN'), ('doi', 'DOI'), ('lccn', 'LCCN'), ('oclc', 'OCLC')], default='isbn', help_text='Select the type of Identifier<div class="right-align"><button type="submit" value="Save and add another" class="waves-effect waves-light btn white-text" name="_continue">Autocomplete</button></div>', max_length=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(default='Title', help_text='Book Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='journal',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='identifier',
            field=models.CharField(choices=[('isbn', 'ISBN'), ('asin', 'ASIN'), ('issn', 'ISSN'), ('doi', 'DOI'), ('lccn', 'LCCN'), ('oclc', 'OCLC')], default='isbn', help_text='Select the type of Identifier<div class="right-align"><button type="submit" value="Save and add another" class="waves-effect waves-light btn white-text" name="_continue">Autocomplete</button></div>', max_length=10),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(default='Title', help_text='Book Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='identifier',
            field=models.CharField(choices=[('isbn', 'ISBN'), ('asin', 'ASIN'), ('issn', 'ISSN'), ('doi', 'DOI'), ('lccn', 'LCCN'), ('oclc', 'OCLC')], default='isbn', help_text='Select the type of Identifier<div class="right-align"><button type="submit" value="Save and add another" class="waves-effect waves-light btn white-text" name="_continue">Autocomplete</button></div>', max_length=10),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title',
            field=models.CharField(default='Title', help_text='Book Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='urls',
            field=models.URLField(blank=True, null=True),
        ),
    ]
