# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('BookManager', '0005_auto_20171026_0438'),
    ]

    operations = [
        migrations.AlterField(
                model_name='book',
                name='accessibility',
                field=models.ForeignKey(help_text='Membership Level Required',
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Member'),
        ),
        migrations.AlterField(
                model_name='book',
                name='copies',
                field=models.IntegerField(default=1, verbose_name='Number of Copies'),
        ),
        migrations.AlterField(
                model_name='book',
                name='genre',
                field=models.CharField(blank=True,
                                       choices=[('Science', 'Science'), ('fiction', 'fiction'), ('Satire', 'Satire'),
                                                ('Drama', 'Drama'), ('Action', 'Action'), ('Adventure', 'Adventure'),
                                                ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Horror', 'Horror'),
                                                ('Selfhelp', 'Selfhelp'), ('Health', 'Health'), ('Guide', 'Guide'),
                                                ('Travel', 'Travel'), ('Children', 'Children'),
                                                ('Religion', 'Religion'), ('Spirituality & New', 'Spirituality & New'),
                                                ('Science', 'Science'), ('History', 'History'), ('Math', 'Math'),
                                                ('Anthology', 'Anthology'), ('Poetry', 'Poetry'),
                                                ('Encyclopedias', 'Encyclopedias'), ('Dictionaries', 'Dictionaries'),
                                                ('Comics', 'Comics'), ('Art', 'Art'), ('Cookbooks', 'Cookbooks'),
                                                ('Diaries', 'Diaries'), ('Journals', 'Journals'), ('Prayer', 'Prayer'),
                                                ('Series', 'Series'), ('Trilogy', 'Trilogy'),
                                                ('Biographies', 'Biographies'), ('Autobiographies', 'Autobiographies'),
                                                ('Fantasy', 'Fantasy')], default='Science', help_text='Book - Genre',
                                       max_length=30),
        ),
        migrations.AlterField(
                model_name='digitalrecords',
                name='accessibility',
                field=models.ForeignKey(help_text='Membership Level Required',
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Member'),
        ),
        migrations.AlterField(
                model_name='digitalrecords',
                name='copies',
                field=models.IntegerField(default=1, verbose_name='Number of Copies'),
        ),
        migrations.AlterField(
                model_name='journal',
                name='accessibility',
                field=models.ForeignKey(help_text='Membership Level Required',
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Member'),
        ),
        migrations.AlterField(
                model_name='journal',
                name='copies',
                field=models.IntegerField(default=1, verbose_name='Number of Copies'),
        ),
        migrations.AlterField(
                model_name='magazine',
                name='accessibility',
                field=models.ForeignKey(help_text='Membership Level Required',
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Member'),
        ),
        migrations.AlterField(
                model_name='magazine',
                name='copies',
                field=models.IntegerField(default=1, verbose_name='Number of Copies'),
        ),
        migrations.AlterField(
                model_name='researchpaper',
                name='accessibility',
                field=models.ForeignKey(help_text='Membership Level Required',
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Member'),
        ),
        migrations.AlterField(
                model_name='researchpaper',
                name='copies',
                field=models.IntegerField(default=1, verbose_name='Number of Copies'),
        ),
    ]
