# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('BookManager', '0006_auto_20171026_1600'),
    ]

    operations = [
        migrations.AlterField(
                model_name='book',
                name='accessibility',
                field=models.ForeignKey(blank=True, help_text='Membership Level Required', null=True,
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Membership'),
        ),
        migrations.AlterField(
                model_name='book',
                name='published_date',
                field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
                model_name='digitalrecords',
                name='accessibility',
                field=models.ForeignKey(blank=True, help_text='Membership Level Required', null=True,
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Membership'),
        ),
        migrations.AlterField(
                model_name='digitalrecords',
                name='published_date',
                field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
                model_name='journal',
                name='accessibility',
                field=models.ForeignKey(blank=True, help_text='Membership Level Required', null=True,
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Membership'),
        ),
        migrations.AlterField(
                model_name='journal',
                name='published_date',
                field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
                model_name='magazine',
                name='accessibility',
                field=models.ForeignKey(blank=True, help_text='Membership Level Required', null=True,
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Membership'),
        ),
        migrations.AlterField(
                model_name='magazine',
                name='published_date',
                field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
                model_name='researchpaper',
                name='accessibility',
                field=models.ForeignKey(blank=True, help_text='Membership Level Required', null=True,
                                        on_delete=django.db.models.deletion.CASCADE, to='UserManager.Membership'),
        ),
        migrations.AlterField(
                model_name='researchpaper',
                name='published_date',
                field=models.DateField(blank=True, null=True),
        ),
    ]
