# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BookManager', '0007_auto_20171026_1608'),
    ]

    operations = [
        migrations.AlterField(
                model_name='book',
                name='authors',
                field=models.CharField(default='Unknown Author',
                                       help_text='Enter the Author names separated by a comma: <br>Eg. good,bad ',
                                       max_length=255),
        ),
        migrations.AlterField(
                model_name='digitalrecords',
                name='authors',
                field=models.CharField(default='Unknown Author',
                                       help_text='Enter the Author names separated by a comma: <br>Eg. good,bad ',
                                       max_length=255),
        ),
        migrations.AlterField(
                model_name='journal',
                name='authors',
                field=models.CharField(default='Unknown Author',
                                       help_text='Enter the Author names separated by a comma: <br>Eg. good,bad ',
                                       max_length=255),
        ),
        migrations.AlterField(
                model_name='magazine',
                name='authors',
                field=models.CharField(default='Unknown Author',
                                       help_text='Enter the Author names separated by a comma: <br>Eg. good,bad ',
                                       max_length=255),
        ),
        migrations.AlterField(
                model_name='researchpaper',
                name='authors',
                field=models.CharField(default='Unknown Author',
                                       help_text='Enter the Author names separated by a comma: <br>Eg. good,bad ',
                                       max_length=255),
        ),
    ]
